security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: plaintext

    providers:
        users_in_memory:
            memory:
                users:
                    admin: { password: admin, roles: [ 'ROLE_USER', 'ROLE_ADMIN' ] }
                    johndoe: { password: johndoe, roles: [ 'ROLE_USER' ] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            form_login:
                provider: users_in_memory
                login_path: /admin/login
                check_path: /admin/login_check
        main:
            pattern: ^/
            provider: users_in_memory


    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
